apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gomanager-fe
  namespace: argocd
spec:
  project: default
  source:
    repoURL: CHANGE_ME_REPO_URL
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: CHANGE_ME_NAMESPACE
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
