apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gomanager-fe
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ridhohardy-bithealth/gomanager-fe.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: gomanager-fe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
