apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomanager-fe
  namespace: CHANGE_ME_NAMESPACE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gomanager-fe
  template:
    metadata:
      labels:
        app: gomanager-fe
    spec:
      imagePullSecrets:
        - name: CHANGE_ME_PULL_SECRET
      containers:
        - name: gomanager-fe
          image: 975049918767.dkr.ecr.ap-southeast-3.amazonaws.com/bth-cloud/gomanager-fe:CHANGE_ME_IMAGE_TAG
          ports:
            - containerPort: 80
