apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomanager-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomanager-fe
      app: gomanager-fe
  template:
    metadata:
      labels:
        app: gomanager-fe
        app: gomanager-fe
    spec:
      # PINNED TO SERVICES NODE GROUP
      nodeSelector:
        karpenter.sh/nodepool: services
      tolerations:
      - key: "node.bth.dev/managed-only"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: gomanager-fe
        image: 975049918767.dkr.ecr.ap-southeast-3.amazonaws.com/bth-cloud/gomanager-fe:150678505fb7a5ab6fc673eb1ebd2f15bbcf8632
        ports:
        - containerPort: 80
---