apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gomanager-fe-ingress
  namespace: gomanager-fe
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/group.name: platform-internal
spec:
  ingressClassName: alb
  rules:
    - host: gomanager-fe.internal.bithealth.co.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gomanager-fe
                port:
                  number: 80
