apiVersion: v1
kind: Service
metadata:
  name: gomanager-fe
  namespace: CHANGE_ME_NAMESPACE
spec:
  selector:
    app: gomanager-fe
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
